SOFTWARES_DIR="${HOME}/.softwares"
SOURCES_DIR="${SOFTWARES_DIR}/sources"
BUILD_DIR="${SOFTWARES_DIR}/build"
INSTALL_DIR="${SOFTWARES_DIR}/install"

MOZILLA_CA_CERT_VERSION="2025-02-25"
OPENSSL_VERSION="3.4.1"